language: python
# sudo false implies containerized builds
#sudo: false
python:
 - "3.5"
 - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install:
    - pip install -r requirements_test.txt
# command to run tests
script:
    - py.test tests/test_hue.py --cov=hue --cov-report term-missing
after_success:
    - coveralls
